// Datos de los proyectos + contenido de caso de estudio.
// El texto es un placeholder realista: reemplazalo cuando tengas lo real.
// Las capturas usan por ahora la imagen que ya tenés (se repite); subí más a
// /public/projects/ y sumalas al array `gallery` / a cada `case`.

export const projects = [
  {
    // El caso completo se arma en components/orbex/. Acá queda solo lo que
    // usa la tarjeta de la landing. Contenido a nivel producto: sin reglas
    // internas de negocio, por privacidad del cliente.
    slug: 'orbex',
    title: 'ORBEX Desarrollos',
    category: 'Desarrollos Inmobiliarios',
    group: 'CRM',
    type: 'web',
    image: '/projects/orbex-login.png',
    tags: ['React', 'Node.js', 'PostgreSQL', 'Meta API'],
    description: 'Sistema comercial propio para una desarrolladora de lotes: cada oportunidad seguida desde el primer contacto hasta el cierre de la venta.',
    lede: 'Sistema comercial propio para gestionar cada oportunidad desde el primer contacto hasta el cierre de la venta.',
    url: '',
    duration: 'Sistema propio en producción, con desarrollo continuo.',
    results: 'Todo el proceso comercial en una sola plataforma.',
    cases: [],
  },
  {
    slug: 'punto-bella-vista',
    title: 'Punto Bella Vista',
    category: 'Concesionaria',
    group: 'Web',
    type: 'web',
    image: '/projects/puntobellavista.png',
    tags: ['Next.js', 'React', 'PostgreSQL', 'Prisma'],
    description: 'Plataforma web para concesionaria multimarca con catálogo de vehículos, sistema de turnos online y panel de administración.',
    lede: 'Plataforma web y panel de gestión para una concesionaria: catálogo de vehículos, turnos online y administración centralizada, todo en un mismo lugar.',
    url: '',
    duration: '8 semanas — del diseño al deploy en producción.',
    results: '+40% de consultas online y gestión de stock centralizada.',
    cases: [
      { title: 'Catálogo con búsqueda inteligente', text: 'Los clientes filtran por marca, modelo, año y precio en segundos. Cada unidad tiene ficha con galería, datos técnicos y contacto directo por WhatsApp.' },
      { title: 'Turnos online sin llamadas', text: 'Reservas de test drive y service sincronizadas con la agenda del local. Menos idas y vueltas por teléfono, más turnos confirmados.' },
      { title: 'Panel de administración', text: 'Alta y edición de vehículos, gestión de turnos y métricas de consultas en un panel simple que el equipo maneja sin depender de nadie.' },
    ],
  },
  {
    slug: 'comextracker',
    title: 'ComexTracker',
    category: 'Comercio Exterior',
    group: 'SaaS',
    type: 'web',
    image: '/projects/comextracker/login.png',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    description: 'Seguimiento de operaciones de comercio exterior: embarques, documentación y estado de cada operación en un solo panel.',
    lede: 'Seguimiento de operaciones de comercio exterior de punta a punta: embarques, documentación y estado de cada operación en un mismo panel.',
    url: '',
    duration: '',
    results: '',
    cases: [],
  },
  {
    slug: 'handprox',
    title: 'HandProX',
    category: 'SaaS Deportivo',
    group: 'SaaS',
    type: 'web',
    image: '/projects/handprox.png',
    tags: ['Next.js', 'Fastify', 'Prisma', 'Socket.io'],
    description: 'Plataforma SaaS de gestión y análisis de handball con estadísticas en vivo, gestión de equipos y ligas.',
    lede: 'Un SaaS para el mundo del handball: estadísticas en vivo, gestión de equipos, jugadores y ligas en una sola plataforma.',
    url: '',
    duration: '12 semanas de desarrollo continuo.',
    results: 'Estadísticas en tiempo real adoptadas por múltiples equipos.',
    cases: [
      { title: 'Estadísticas en vivo', text: 'Carga de eventos partido a partido con actualización en tiempo real vía websockets. Rankings y métricas que se calculan solos.' },
      { title: 'Gestión de equipos y ligas', text: 'Altas de jugadores, planteles, fixtures y tablas de posiciones. Todo el torneo administrado desde un solo lugar.' },
    ],
  },
  {
    slug: 'fleur-co',
    title: 'Fleur & Co',
    category: 'E-Commerce',
    group: 'E-Commerce',
    type: 'web',
    image: '/projects/flores.png',
    tags: ['Next.js', 'TypeScript', 'Prisma', 'MercadoPago'],
    description: 'E-Commerce premium de flores artificiales con carrito, checkout, MercadoPago integrado y panel admin.',
    lede: 'Una tienda online premium de flores artificiales: catálogo cuidado, carrito, checkout con MercadoPago y panel de administración.',
    url: '',
    duration: '6 semanas.',
    results: 'Ventas online operando de punta a punta.',
    cases: [
      { title: 'Compra sin fricción', text: 'Catálogo con variantes, carrito persistente y checkout con MercadoPago integrado para pagar en segundos.' },
      { title: 'Panel de gestión', text: 'Alta de productos, control de stock y seguimiento de pedidos desde un panel pensado para no-técnicos.' },
    ],
  },
  {
    slug: 'celebria',
    title: 'Celebria',
    category: 'Invitaciones Digitales',
    group: 'Web',
    type: 'web',
    image: '/projects/celebria.png',
    tags: ['Next.js', 'TypeScript', 'Prisma', 'Framer Motion'],
    description: 'Plataforma de invitaciones digitales interactivas con templates premium, editor en tiempo real y gestión de RSVP.',
    lede: 'Invitaciones digitales interactivas: templates premium, editor en tiempo real y gestión de confirmaciones (RSVP) para cada evento.',
    url: '',
    duration: '10 semanas.',
    results: 'Invitaciones creadas y enviadas por los propios usuarios.',
    cases: [
      { title: 'Editor en tiempo real', text: 'Los usuarios personalizan su invitación y ven los cambios al instante, sin saber nada de diseño.' },
      { title: 'RSVP y gestión de invitados', text: 'Confirmaciones online, lista de invitados y recordatorios, todo centralizado para el organizador.' },
    ],
  },
  {
    slug: 'bar-app',
    title: 'Bar — App',
    category: 'Gastronomía',
    group: 'Mobile',
    type: 'mobile',
    image: '/projects/rotta-app.png',
    tags: ['React', 'NestJS', 'PostgreSQL', 'Redis'],
    description: 'Aplicación mobile para clientes del bar con wallet digital, sistema VIP, pedidos desde la mesa y reservas con QR.',
    lede: 'La app mobile de un bar: wallet digital, beneficios VIP, pedidos desde la mesa y reservas con QR para fidelizar a los clientes.',
    url: '',
    duration: '14 semanas (app + backend).',
    results: 'Más recurrencia y ticket promedio con el programa VIP.',
    cases: [
      { title: 'Pedidos desde la mesa', text: 'El cliente escanea un QR, pide y paga desde el celular. Menos filas, más rotación.' },
      { title: 'Wallet y beneficios VIP', text: 'Saldo digital, niveles y recompensas que incentivan a volver. Gamificación aplicada al negocio.' },
    ],
  },
  {
    slug: 'bar-admin',
    title: 'Bar — Admin',
    category: 'Gastronomía',
    group: 'Web',
    type: 'web',
    image: '/projects/rotta-admin.png',
    tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Redis'],
    description: 'Panel de administración con métricas en tiempo real, gestión de pedidos, reservas, eventos y gamificación.',
    lede: 'El panel de control del bar: métricas en vivo, gestión de pedidos y reservas, eventos y el sistema de gamificación de la app.',
    url: '',
    duration: 'Desarrollado junto a la app.',
    results: 'Operación del local centralizada en un solo panel.',
    cases: [
      { title: 'Métricas en tiempo real', text: 'Ventas, mesas y reservas del día en vivo, para tomar decisiones sobre la marcha.' },
      { title: 'Gestión integral', text: 'Pedidos, reservas, eventos y recompensas administrados desde un mismo lugar.' },
    ],
  },
  {
    slug: 'pintureria',
    title: 'Pinturería',
    category: 'E-Commerce',
    group: 'E-Commerce',
    type: 'web',
    image: '/projects/pintureria.png',
    tags: ['Next.js', 'React', 'Tailwind', 'OpenAI'],
    description: 'E-Commerce de pinturas con asistente IA que calcula materiales, catálogo de +500 productos y buscador de sucursales.',
    lede: 'Un e-commerce de pinturas con un asistente de IA que calcula cuánta pintura necesitás, catálogo de +500 productos y buscador de sucursales.',
    url: '',
    duration: '9 semanas.',
    results: 'Menos consultas repetitivas gracias al asistente IA.',
    cases: [
      { title: 'Asistente con IA', text: 'El cliente ingresa metros y tipo de superficie y la IA le dice cuánta pintura comprar. Menos errores, más ventas.' },
      { title: 'Catálogo grande y buscable', text: 'Más de 500 productos organizados y filtrables, con buscador de sucursales por cercanía.' },
    ],
  },
  {
    slug: 'padelleague',
    title: 'PadelLeague',
    category: 'SaaS Deportivo',
    group: 'SaaS',
    type: 'web',
    image: '/projects/padelleague.png',
    tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Stripe'],
    description: 'Plataforma SaaS para torneos de pádel con fixtures automáticos, rankings en tiempo real y gestión de pagos.',
    lede: 'Un SaaS para organizar torneos de pádel: fixtures automáticos, rankings en tiempo real y cobro de inscripciones con Stripe.',
    url: '',
    duration: '11 semanas.',
    results: 'Torneos gestionados de principio a fin sin planillas.',
    cases: [
      { title: 'Fixtures automáticos', text: 'Se arman los cruces y el calendario solos a partir de los inscriptos. Cero armado manual.' },
      { title: 'Rankings y pagos', text: 'Ranking en vivo y cobro de inscripciones online con Stripe, todo integrado.' },
    ],
  },
  {
    // Contenido a nivel producto, tomado del documento del portal.
    slug: 'aguilasoft',
    title: 'AguilaSoft',
    category: 'Portal B2B para distribuidoras',
    group: 'SaaS',
    type: 'web',
    image: '/projects/aguilasoft/home.png',
    // Si hay logo, la carta destacada lo muestra en lugar del título escrito
    logo: '/projects/aguilasoft/logo.png',
    tags: ['Portal web', 'WhatsApp API', 'Multiempresa', 'IA'],
    description: 'Portal de autogestión para los clientes de una distribuidora: cuenta corriente, catálogo con su propio precio, pedidos y seguimiento, en la web y por WhatsApp.',
    lede: 'El teléfono deja de sonar. Una distribuidora atiende a cientos de comercios y todo el día entran los mismos cuatro llamados: cuánto debo, mandame la lista, tenés stock, en qué anda mi pedido. El portal es la puerta para que el cliente entre solo, a cualquier hora, y vea sus datos sin que nadie los busque por él.',
    url: '',
    duration: 'En producción, con varias distribuidoras activas.',
    results: 'Cuatro llamados menos por día: saldo, precios, stock y pedidos disponibles un domingo a la noche.',
    cases: [
      { title: 'Su precio, no una lista genérica', text: 'Cada cliente ve lo que él paga: su lista, su descuento y los precios acordados, ya aplicados. Busca por código, nombre o descripción —y según la empresa, también por código de fabricante o equivalencia— con fotos y filtros que cada distribuidora define.' },
      { title: 'La cuenta corriente, clara', text: 'Cuánto debe, qué está vencido y qué vence pronto, separado por antigüedad y no en un número suelto. Filtra por fecha y tipo de comprobante, abre el detalle de una factura con sus renglones y se baja el resumen en Excel o PDF.' },
      { title: 'Pedidos de punta a punta', text: 'Arma el pedido desde el catálogo o pegando una lista de códigos, elige fecha de entrega y sucursal, y lo manda. Después sigue en qué etapa está cada uno —enviado, aceptado, en preparación, facturado— con el avance por unidades y un botón para repetir un pedido anterior entero.' },
      { title: 'Un bot de WhatsApp por empresa', text: 'Lo mismo que el portal, por el canal donde la gente ya está, y con el número de cada distribuidora. Responde saldo, precios, stock y estado de pedidos; nunca redacta un número: los datos salen del sistema en el momento. Cuando el cliente lo pide, se calla y la conversación aparece sin leer en el panel del proveedor.' },
      { title: 'El panel del proveedor', text: 'La empresa maneja su portal sin pedirle nada a nadie: define qué ve cada cliente, su logo y su color, el vocabulario de su rubro, y sube las fotos de producto en tanda. Las facturas de proveedor se leen solas del PDF y se revisan antes de entrar al sistema.' },
      { title: 'Lee en vivo, no copia datos', text: 'El portal lee la base del sistema de gestión en el momento: no hay sincronización nocturna ni datos de ayer. Y solo escribe en un lugar —la bandeja de pedidos—; no emite comprobantes, no imputa en cuenta corriente y no mueve stock. La base del cliente no se toca.' },
      { title: 'Un sistema, muchos portales', text: 'Cada empresa entra por su propio subdominio y ve su portal, con su marca y sus reglas. Es el mismo sistema: lo que se arregla o se mejora aparece en todos a la vez. Para el cliente final, es el portal de su proveedor.' },
    ],
  },
  {
    // El caso completo se arma en components/gestio/.
    slug: 'gestio',
    title: 'Gestio',
    category: 'Sistema de Gestión',
    group: 'SaaS',
    type: 'web',
    image: '/projects/gestio/login.png',
    tags: ['React', 'Node.js', 'PostgreSQL'],
    description: 'Panel de gestión para un negocio: pedidos, clientes, mercadería, proveedores, gastos y seguimiento comercial en una sola vista.',
    lede: 'Todo el negocio en una sola vista: pedidos, clientes, mercadería, proveedores, gastos y seguimiento comercial en un mismo panel.',
    url: '',
    duration: '',
    results: '',
    cases: [],
  },
]

// Los casos que van como cartas largas, en este orden. Un null reserva el
// contenedor de un caso todavía por definir.
export const featuredSlugs = ['orbex', 'punto-bella-vista', 'comextracker', 'aguilasoft', 'gestio']

export const getProject = (slug) => projects.find((p) => p.slug === slug)
