// Datos de los proyectos + contenido de caso de estudio.
// El texto es un placeholder realista: reemplazalo cuando tengas lo real.
// Las capturas usan por ahora la imagen que ya tenés (se repite); subí más a
// /public/projects/ y sumalas al array `gallery` / a cada `case`.

export const projects = [
  {
    slug: 'orbex-crm',
    title: 'ORBEX Desarrollos',
    category: 'CRM Comercial',
    group: 'SaaS',
    type: 'web',
    image: '/projects/orbex.png',
    tags: ['Next.js', 'React', 'SQLite', 'Meta Lead Ads'],
    description: 'CRM comercial para una desarrolladora inmobiliaria: captura de leads de Meta, reparto automático entre equipos y seguimiento en un embudo kanban.',
    lede: 'El sistema comercial propio de ORBEX Desarrollos: los leads de Facebook e Instagram entran solos, se reparten entre los equipos sin mezclarse y cada venta se sigue de principio a fin.',
    url: '',
    duration: 'Fase 1 funcional, en uso por el equipo comercial.',
    results: 'Cada lead seguido de punta a punta, sin que se escape ninguno.',
    cases: [
      { title: 'Panel comercial en vivo', text: 'Un tablero con los KPIs del día —leads totales, sin asignar, activos en el embudo y ventas ganadas— y el rendimiento de cada equipo en tiempo real.', image: '/projects/orbex-panel.png' },
      { title: 'Embudo de ventas kanban', text: 'Cada lead avanza por etapas (Nuevo, Contactar, En proceso, Visita agendada, Reserva, Vendido). Se arrastra la tarjeta entre columnas y el equipo ve el pipeline completo.', image: '/projects/orbex.png' },
      { title: 'Reparto automático de leads', text: 'Los leads de las campañas de Meta entran solos y se reparten en round-robin entre los equipos. Cada supervisora los deriva a un vendedor. Nada se mezcla ni se pierde.', image: '/projects/orbex-asignacion.png' },
      { title: 'Ficha de gestión de cada lead', text: 'Toda la gestión en un lugar: contacto directo por WhatsApp, llamada o email, calificación (frío, tibio, caliente), etapa del embudo y notas de seguimiento.', image: '/projects/orbex-ficha.png' },
    ],
    testimonial: { text: 'Pasamos de perder leads en un Excel a tener cada oportunidad seguida de principio a fin. Ahora sabemos exactamente en qué está cada venta.', name: 'Nombre Apellido', role: 'Gerencia Comercial · ORBEX Desarrollos' },
  },
  {
    slug: 'comextracker',
    title: 'ComexTracker',
    category: 'Comercio Exterior',
    group: 'SaaS',
    type: 'web',
    image: '/projects/comextracker.png',
    tags: ['Next.js', 'PostgreSQL', 'Prisma', 'PWA'],
    description: 'Plataforma de seguimiento de operaciones para despachantes de aduana: cada importador ve su carga en vivo, con avisos de vencimientos y mensajes.',
    lede: 'El despachante carga y actualiza sus operaciones, y cada cliente entra con su usuario a ver solo sus cargas —con una línea de progreso, avisos de vencimientos y mensajes con el despachante.',
    url: '',
    duration: 'Plataforma multi-tenant en producción.',
    results: 'El importador ve su carga en tiempo real. Menos llamados, menos vencimientos perdidos.',
    cases: [
      { title: 'Tablero del despachante', text: 'Todas las operaciones en un panel: KPIs de cargas en viaje, en aduana, para retirar y entregadas, con estados de embarque y despacho por cliente.', image: '/projects/comextracker.png' },
      { title: 'Seguimiento en vivo para el cliente', text: 'Cada importador ve sus operaciones con una línea de progreso de 5 etapas —Apertura, Embarque, Presupuesto, Despacho, Liberado— actualizada en tiempo real.', image: '/projects/comextracker-cliente.png' },
      { title: 'Cada operación, paso a paso', text: 'El detalle de la carga: canal de despacho, formularios (ANMAT), fechas, carátula imprimible y mensajería directa con el despachante.', image: '/projects/comextracker-operacion.png' },
      { title: 'Pipeline configurable', text: 'Las reglas que deciden qué luz se prende son configurables por despachante, con avisos automáticos de vencimientos por email y push.', image: '/projects/comextracker-pipeline.png' },
    ],
    testimonial: { text: 'Antes vivía contestando “¿dónde está mi carga?”. Ahora el cliente lo ve solo, en vivo. Nos ahorró horas todos los días.', name: 'Nombre Apellido', role: 'Despachante · Integral Logistics' },
  },
  {
    slug: 'padelya',
    title: 'PadelYa',
    category: 'Plataforma Deportiva',
    group: 'SaaS',
    type: 'web',
    image: '/projects/padelya.png',
    tags: ['Next.js', 'PostgreSQL', 'Prisma', 'NextAuth'],
    description: 'Plataforma de pádel: los jugadores reservan canchas online y los clubes gestionan reservas, agenda e ingresos desde un panel.',
    lede: 'Una plataforma completa para el mundo del pádel: los jugadores buscan y reservan canchas por zona, y los clubes manejan reservas, agenda, torneos y rankings desde su propio panel.',
    url: '',
    duration: 'Plataforma completa (jugadores + clubes).',
    results: 'Reservas online 24/7 y clubes con su agenda ordenada en un solo lugar.',
    cases: [
      { title: 'Reservás tu cancha online', text: 'El jugador elige día, horario y cancha desde la disponibilidad en vivo del club. Sin llamados ni idas y vueltas por WhatsApp.', image: '/projects/padelya.png' },
      { title: 'Buscá canchas por zona', text: 'Listado de clubes con filtros por zona y precio, para encontrar dónde jugar en segundos.', image: '/projects/padelya-buscar.png' },
      { title: 'El panel del club', text: 'El club gestiona todo desde un dashboard: reservas del día, ocupación, ingresos, agenda y sus canchas.', image: '/projects/padelya-club.png' },
      { title: 'Torneos y rankings', text: 'Circuitos, torneos con fixtures automáticos y rankings por categoría argentina (8va a 1ra).', image: '/projects/padelya-ranking.png' },
    ],
    testimonial: { text: 'Los jugadores reservan solos y nosotros dejamos de perder turnos por WhatsApp. El club quedó mucho más ordenado.', name: 'Nombre Apellido', role: 'Dueño · Club de Pádel' },
  },
  {
    slug: 'punto-bella-vista',
    title: 'Punto Bella Vista',
    category: 'Concesionaria',
    group: 'Web',
    type: 'web',
    image: '/projects/puntobellavista.png',
    tags: ['Next.js', 'React', 'PostgreSQL', 'Prisma'],
    description: 'Plataforma web para concesionaria multimarca con catálogo de vehículos, sistema de turnos online y panel de administración.',
    lede: 'Plataforma web y panel de gestión para una concesionaria: catálogo de vehículos, turnos online y administración centralizada, todo en un mismo lugar.',
    url: '',
    duration: '8 semanas — del diseño al deploy en producción.',
    results: '+40% de consultas online y gestión de stock centralizada.',
    cases: [
      { title: 'Catálogo con búsqueda inteligente', text: 'Los clientes filtran por marca, modelo, año y precio en segundos. Cada unidad tiene ficha con galería, datos técnicos y contacto directo por WhatsApp.' },
      { title: 'Turnos online sin llamadas', text: 'Reservas de test drive y service sincronizadas con la agenda del local. Menos idas y vueltas por teléfono, más turnos confirmados.' },
      { title: 'Panel de administración', text: 'Alta y edición de vehículos, gestión de turnos y métricas de consultas en un panel simple que el equipo maneja sin depender de nadie.' },
    ],
    testimonial: { text: 'Margon entendió el negocio y nos dejó una herramienta que usamos todos los días. Las consultas por la web se dispararon.', name: 'Nombre Apellido', role: 'Dueño · Punto Bella Vista' },
  },
  {
    slug: 'handprox',
    title: 'HandProX',
    category: 'SaaS Deportivo',
    group: 'SaaS',
    type: 'web',
    image: '/projects/handprox.png',
    tags: ['Next.js', 'Fastify', 'Prisma', 'Socket.io'],
    description: 'Plataforma SaaS de gestión y análisis de handball con estadísticas en vivo, gestión de equipos y ligas.',
    lede: 'Un SaaS para el mundo del handball: estadísticas en vivo, gestión de equipos, jugadores y ligas en una sola plataforma.',
    url: '',
    duration: '12 semanas de desarrollo continuo.',
    results: 'Estadísticas en tiempo real adoptadas por múltiples equipos.',
    cases: [
      { title: 'Estadísticas en vivo', text: 'Carga de eventos partido a partido con actualización en tiempo real vía websockets. Rankings y métricas que se calculan solos.' },
      { title: 'Gestión de equipos y ligas', text: 'Altas de jugadores, planteles, fixtures y tablas de posiciones. Todo el torneo administrado desde un solo lugar.' },
    ],
    testimonial: { text: 'Pasamos de las planillas de Excel a tener todo en vivo. Un cambio total para la liga.', name: 'Nombre Apellido', role: 'Coordinador · HandProX' },
  },
  {
    slug: 'sinnergia',
    title: 'Sinnergia',
    category: 'Marketing Digital',
    group: 'Web',
    type: 'web',
    image: '/projects/sinnergia.png',
    tags: ['Next.js', 'React', 'Tailwind', 'Framer Motion'],
    description: 'Landing page premium para agencia de marketing digital con animaciones, portfolio dinámico y formulario de contacto.',
    lede: 'Una landing premium para una agencia de marketing: animaciones cuidadas, portfolio dinámico y un embudo de contacto claro.',
    url: '',
    duration: '4 semanas.',
    results: 'Más consultas calificadas desde el sitio.',
    cases: [
      { title: 'Diseño con movimiento', text: 'Animaciones sutiles al hacer scroll que guían la atención sin distraer, transmitiendo el nivel de la agencia.' },
      { title: 'Portfolio y contacto', text: 'Casos destacados con carga dinámica y un formulario de contacto directo al equipo comercial.' },
    ],
    testimonial: { text: 'La web quedó a la altura de lo que ofrecemos. Nos representa perfecto.', name: 'Nombre Apellido', role: 'Directora · Sinnergia' },
  },
  {
    slug: 'fleur-co',
    title: 'Fleur & Co',
    category: 'E-Commerce',
    group: 'E-Commerce',
    type: 'web',
    image: '/projects/flores.png',
    tags: ['Next.js', 'TypeScript', 'Prisma', 'MercadoPago'],
    description: 'E-Commerce premium de flores artificiales con carrito, checkout, MercadoPago integrado y panel admin.',
    lede: 'Una tienda online premium de flores artificiales: catálogo cuidado, carrito, checkout con MercadoPago y panel de administración.',
    url: '',
    duration: '6 semanas.',
    results: 'Ventas online operando de punta a punta.',
    cases: [
      { title: 'Compra sin fricción', text: 'Catálogo con variantes, carrito persistente y checkout con MercadoPago integrado para pagar en segundos.' },
      { title: 'Panel de gestión', text: 'Alta de productos, control de stock y seguimiento de pedidos desde un panel pensado para no-técnicos.' },
    ],
    testimonial: { text: 'Empezamos a vender online sin complicaciones. El panel es súper fácil de usar.', name: 'Nombre Apellido', role: 'Fundadora · Fleur & Co' },
  },
  {
    slug: 'celebria',
    title: 'Celebria',
    category: 'Invitaciones Digitales',
    group: 'Web',
    type: 'web',
    image: '/projects/celebria.png',
    tags: ['Next.js', 'TypeScript', 'Prisma', 'Framer Motion'],
    description: 'Plataforma de invitaciones digitales interactivas con templates premium, editor en tiempo real y gestión de RSVP.',
    lede: 'Invitaciones digitales interactivas: templates premium, editor en tiempo real y gestión de confirmaciones (RSVP) para cada evento.',
    url: '',
    duration: '10 semanas.',
    results: 'Invitaciones creadas y enviadas por los propios usuarios.',
    cases: [
      { title: 'Editor en tiempo real', text: 'Los usuarios personalizan su invitación y ven los cambios al instante, sin saber nada de diseño.' },
      { title: 'RSVP y gestión de invitados', text: 'Confirmaciones online, lista de invitados y recordatorios, todo centralizado para el organizador.' },
    ],
    testimonial: { text: 'Nuestros clientes arman su invitación solos y quedan fascinados. Nos ahorró muchísimo tiempo.', name: 'Nombre Apellido', role: 'Fundador · Celebria' },
  },
  {
    slug: 'bar-app',
    title: 'Bar — App',
    category: 'Gastronomía',
    group: 'Mobile',
    type: 'mobile',
    image: '/projects/rotta-app.png',
    tags: ['React', 'NestJS', 'PostgreSQL', 'Redis'],
    description: 'Aplicación mobile para clientes del bar con wallet digital, sistema VIP, pedidos desde la mesa y reservas con QR.',
    lede: 'La app mobile de un bar: wallet digital, beneficios VIP, pedidos desde la mesa y reservas con QR para fidelizar a los clientes.',
    url: '',
    duration: '14 semanas (app + backend).',
    results: 'Más recurrencia y ticket promedio con el programa VIP.',
    cases: [
      { title: 'Pedidos desde la mesa', text: 'El cliente escanea un QR, pide y paga desde el celular. Menos filas, más rotación.' },
      { title: 'Wallet y beneficios VIP', text: 'Saldo digital, niveles y recompensas que incentivan a volver. Gamificación aplicada al negocio.' },
    ],
    testimonial: { text: 'La app cambió la experiencia del bar. Los clientes la aman y vuelven más seguido.', name: 'Nombre Apellido', role: 'Dueño · Bar' },
  },
  {
    slug: 'bar-admin',
    title: 'Bar — Admin',
    category: 'Gastronomía',
    group: 'Web',
    type: 'web',
    image: '/projects/rotta-admin.png',
    tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Redis'],
    description: 'Panel de administración con métricas en tiempo real, gestión de pedidos, reservas, eventos y gamificación.',
    lede: 'El panel de control del bar: métricas en vivo, gestión de pedidos y reservas, eventos y el sistema de gamificación de la app.',
    url: '',
    duration: 'Desarrollado junto a la app.',
    results: 'Operación del local centralizada en un solo panel.',
    cases: [
      { title: 'Métricas en tiempo real', text: 'Ventas, mesas y reservas del día en vivo, para tomar decisiones sobre la marcha.' },
      { title: 'Gestión integral', text: 'Pedidos, reservas, eventos y recompensas administrados desde un mismo lugar.' },
    ],
    testimonial: { text: 'Tengo todo el bar en una pantalla. No vuelvo atrás.', name: 'Nombre Apellido', role: 'Encargado · Bar' },
  },
  {
    slug: 'pintureria',
    title: 'Pinturería',
    category: 'E-Commerce',
    group: 'E-Commerce',
    type: 'web',
    image: '/projects/pintureria.png',
    tags: ['Next.js', 'React', 'Tailwind', 'OpenAI'],
    description: 'E-Commerce de pinturas con asistente IA que calcula materiales, catálogo de +500 productos y buscador de sucursales.',
    lede: 'Un e-commerce de pinturas con un asistente de IA que calcula cuánta pintura necesitás, catálogo de +500 productos y buscador de sucursales.',
    url: '',
    duration: '9 semanas.',
    results: 'Menos consultas repetitivas gracias al asistente IA.',
    cases: [
      { title: 'Asistente con IA', text: 'El cliente ingresa metros y tipo de superficie y la IA le dice cuánta pintura comprar. Menos errores, más ventas.' },
      { title: 'Catálogo grande y buscable', text: 'Más de 500 productos organizados y filtrables, con buscador de sucursales por cercanía.' },
    ],
    testimonial: { text: 'El calculador con IA fue un golazo. Los clientes compran justo lo que necesitan.', name: 'Nombre Apellido', role: 'Gerente · Pinturería' },
  },
  {
    slug: 'padelleague',
    title: 'PadelLeague',
    category: 'SaaS Deportivo',
    group: 'SaaS',
    type: 'web',
    image: '/projects/padelleague.png',
    tags: ['Next.js', 'NestJS', 'PostgreSQL', 'Stripe'],
    description: 'Plataforma SaaS para torneos de pádel con fixtures automáticos, rankings en tiempo real y gestión de pagos.',
    lede: 'Un SaaS para organizar torneos de pádel: fixtures automáticos, rankings en tiempo real y cobro de inscripciones con Stripe.',
    url: '',
    duration: '11 semanas.',
    results: 'Torneos gestionados de principio a fin sin planillas.',
    cases: [
      { title: 'Fixtures automáticos', text: 'Se arman los cruces y el calendario solos a partir de los inscriptos. Cero armado manual.' },
      { title: 'Rankings y pagos', text: 'Ranking en vivo y cobro de inscripciones online con Stripe, todo integrado.' },
    ],
    testimonial: { text: 'Organizar un torneo pasó de días a minutos. Impecable.', name: 'Nombre Apellido', role: 'Organizador · PadelLeague' },
  },
]

export const getProject = (slug) => projects.find((p) => p.slug === slug)
